version: '3.4'

services:
  web:
    container_name: web
    image: web-server:latest
    ports:
      - "3000:8081"
    environment:
      CLUSTER: ${DB_CLUSTER}
      USER: ${DB_USER}
      PASS: ${DB_PASS}
      SLOT_URI: slot:8088
    networks:
      - slot
  slot-rpc:
    container_name: slot
    image: slot-server:latest
    restart: always
    networks:
      - slot

networks:
    slot:
