[[SlotGames]]
id = 0
parSheet = "foodie.toml"
open = true

#[[SlotGames]]
#id = 1
#gameName = "CandyParty"
#open = true
#
#[[SlotGames]]
#id = 2
#gameName = "AlchemistCat"
#open = true
#
#[[SlotGames]]
#id = 3
#gameName = "FortuneDragon"
#open = true