// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: dragon.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Jackpot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Win     float32 `protobuf:"fixed32,1,opt,name=win,proto3" json:"win,omitempty"`
	Jackpot uint32  `protobuf:"varint,2,opt,name=jackpot,proto3" json:"jackpot,omitempty"`
}

func (x *Jackpot) Reset() {
	*x = Jackpot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dragon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jackpot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jackpot) ProtoMessage() {}

func (x *Jackpot) ProtoReflect() protoreflect.Message {
	mi := &file_dragon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jackpot.ProtoReflect.Descriptor instead.
func (*Jackpot) Descriptor() ([]byte, []int) {
	return file_dragon_proto_rawDescGZIP(), []int{0}
}

func (x *Jackpot) GetWin() float32 {
	if x != nil {
		return x.Win
	}
	return 0
}

func (x *Jackpot) GetJackpot() uint32 {
	if x != nil {
		return x.Jackpot
	}
	return 0
}

type DragonReelResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res     *BaseResult `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Free    *FreeSpin   `protobuf:"bytes,2,opt,name=free,proto3" json:"free,omitempty"`
	Jackpot *Jackpot    `protobuf:"bytes,3,opt,name=jackpot,proto3" json:"jackpot,omitempty"`
}

func (x *DragonReelResult) Reset() {
	*x = DragonReelResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dragon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonReelResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonReelResult) ProtoMessage() {}

func (x *DragonReelResult) ProtoReflect() protoreflect.Message {
	mi := &file_dragon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonReelResult.ProtoReflect.Descriptor instead.
func (*DragonReelResult) Descriptor() ([]byte, []int) {
	return file_dragon_proto_rawDescGZIP(), []int{1}
}

func (x *DragonReelResult) GetRes() *BaseResult {
	if x != nil {
		return x.Res
	}
	return nil
}

func (x *DragonReelResult) GetFree() *FreeSpin {
	if x != nil {
		return x.Free
	}
	return nil
}

func (x *DragonReelResult) GetJackpot() *Jackpot {
	if x != nil {
		return x.Jackpot
	}
	return nil
}

var File_dragon_proto protoreflect.FileDescriptor

var file_dragon_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x64, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x73, 0x6c, 0x6f, 0x74, 0x1a, 0x11, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x62, 0x61, 0x73,
	0x65, 0x2f, 0x66, 0x72, 0x65, 0x65, 0x73, 0x70, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x35, 0x0a, 0x07, 0x4a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x77,
	0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x77, 0x69, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x6a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x6a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x22, 0x83, 0x01, 0x0a, 0x10, 0x44, 0x72, 0x61, 0x67,
	0x6f, 0x6e, 0x52, 0x65, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x22, 0x0a, 0x03,
	0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x6c, 0x6f, 0x74,
	0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x03, 0x72, 0x65, 0x73,
	0x12, 0x22, 0x0a, 0x04, 0x66, 0x72, 0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x73, 0x6c, 0x6f, 0x74, 0x2e, 0x46, 0x72, 0x65, 0x65, 0x53, 0x70, 0x69, 0x6e, 0x52, 0x04,
	0x66, 0x72, 0x65, 0x65, 0x12, 0x27, 0x0a, 0x07, 0x6a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x6c, 0x6f, 0x74, 0x2e, 0x4a, 0x61, 0x63,
	0x6b, 0x70, 0x6f, 0x74, 0x52, 0x07, 0x6a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x32, 0x3b, 0x0a,
	0x0a, 0x44, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x65, 0x6c, 0x12, 0x2d, 0x0a, 0x04, 0x53,
	0x70, 0x69, 0x6e, 0x12, 0x0d, 0x2e, 0x73, 0x6c, 0x6f, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x73, 0x6c, 0x6f, 0x74, 0x2e, 0x44, 0x72, 0x61, 0x67, 0x6f, 0x6e,
	0x52, 0x65, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dragon_proto_rawDescOnce sync.Once
	file_dragon_proto_rawDescData = file_dragon_proto_rawDesc
)

func file_dragon_proto_rawDescGZIP() []byte {
	file_dragon_proto_rawDescOnce.Do(func() {
		file_dragon_proto_rawDescData = protoimpl.X.CompressGZIP(file_dragon_proto_rawDescData)
	})
	return file_dragon_proto_rawDescData
}

var file_dragon_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dragon_proto_goTypes = []interface{}{
	(*Jackpot)(nil),          // 0: slot.Jackpot
	(*DragonReelResult)(nil), // 1: slot.DragonReelResult
	(*BaseResult)(nil),       // 2: slot.BaseResult
	(*FreeSpin)(nil),         // 3: slot.FreeSpin
	(*Request)(nil),          // 4: slot.Request
}
var file_dragon_proto_depIdxs = []int32{
	2, // 0: slot.DragonReelResult.res:type_name -> slot.BaseResult
	3, // 1: slot.DragonReelResult.free:type_name -> slot.FreeSpin
	0, // 2: slot.DragonReelResult.jackpot:type_name -> slot.Jackpot
	4, // 3: slot.DragonReel.Spin:input_type -> slot.Request
	1, // 4: slot.DragonReel.Spin:output_type -> slot.DragonReelResult
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_dragon_proto_init() }
func file_dragon_proto_init() {
	if File_dragon_proto != nil {
		return
	}
	file_base_result_proto_init()
	file_base_request_proto_init()
	file_base_freespin_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_dragon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jackpot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dragon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonReelResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dragon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dragon_proto_goTypes,
		DependencyIndexes: file_dragon_proto_depIdxs,
		MessageInfos:      file_dragon_proto_msgTypes,
	}.Build()
	File_dragon_proto = out.File
	file_dragon_proto_rawDesc = nil
	file_dragon_proto_goTypes = nil
	file_dragon_proto_depIdxs = nil
}
