// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: main.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res *BaseResult `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	// Types that are assignable to Bonus:
	//
	//	*SpinResponse_Foodie
	//	*SpinResponse_Dragon
	Bonus isSpinResponse_Bonus `protobuf_oneof:"bonus"`
}

func (x *SpinResponse) Reset() {
	*x = SpinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinResponse) ProtoMessage() {}

func (x *SpinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinResponse.ProtoReflect.Descriptor instead.
func (*SpinResponse) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{0}
}

func (x *SpinResponse) GetRes() *BaseResult {
	if x != nil {
		return x.Res
	}
	return nil
}

func (m *SpinResponse) GetBonus() isSpinResponse_Bonus {
	if m != nil {
		return m.Bonus
	}
	return nil
}

func (x *SpinResponse) GetFoodie() *FoodieBonus {
	if x, ok := x.GetBonus().(*SpinResponse_Foodie); ok {
		return x.Foodie
	}
	return nil
}

func (x *SpinResponse) GetDragon() *DragonBonus {
	if x, ok := x.GetBonus().(*SpinResponse_Dragon); ok {
		return x.Dragon
	}
	return nil
}

type isSpinResponse_Bonus interface {
	isSpinResponse_Bonus()
}

type SpinResponse_Foodie struct {
	Foodie *FoodieBonus `protobuf:"bytes,2,opt,name=foodie,proto3,oneof"`
}

type SpinResponse_Dragon struct {
	Dragon *DragonBonus `protobuf:"bytes,3,opt,name=dragon,proto3,oneof"`
}

func (*SpinResponse_Foodie) isSpinResponse_Bonus() {}

func (*SpinResponse_Dragon) isSpinResponse_Bonus() {}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpinResponse *SpinResponse `protobuf:"bytes,1,opt,name=spinResponse,proto3" json:"spinResponse,omitempty"`
	State        string        `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetSpinResponse() *SpinResponse {
	if x != nil {
		return x.SpinResponse
	}
	return nil
}

func (x *Response) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_main_proto protoreflect.FileDescriptor

var file_main_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x73, 0x6c,
	0x6f, 0x74, 0x1a, 0x12, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x66, 0x6f, 0x6f, 0x64, 0x69,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x64, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x95, 0x01, 0x0a, 0x0c, 0x53, 0x70, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x6c, 0x6f, 0x74, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x03, 0x72, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x06, 0x66, 0x6f,
	0x6f, 0x64, 0x69, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x6c, 0x6f,
	0x74, 0x2e, 0x46, 0x6f, 0x6f, 0x64, 0x69, 0x65, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x48, 0x00, 0x52,
	0x06, 0x66, 0x6f, 0x6f, 0x64, 0x69, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x64, 0x72, 0x61, 0x67, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x6c, 0x6f, 0x74, 0x2e, 0x44,
	0x72, 0x61, 0x67, 0x6f, 0x6e, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x48, 0x00, 0x52, 0x06, 0x64, 0x72,
	0x61, 0x67, 0x6f, 0x6e, 0x42, 0x07, 0x0a, 0x05, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x22, 0x58, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0c, 0x73, 0x70, 0x69,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x73, 0x6c, 0x6f, 0x74, 0x2e, 0x53, 0x70, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x0c, 0x73, 0x70, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x32, 0x2d, 0x0a, 0x04, 0x53, 0x6c, 0x6f, 0x74, 0x12,
	0x25, 0x0a, 0x04, 0x53, 0x70, 0x69, 0x6e, 0x12, 0x0d, 0x2e, 0x73, 0x6c, 0x6f, 0x74, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x73, 0x6c, 0x6f, 0x74, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_main_proto_rawDescOnce sync.Once
	file_main_proto_rawDescData = file_main_proto_rawDesc
)

func file_main_proto_rawDescGZIP() []byte {
	file_main_proto_rawDescOnce.Do(func() {
		file_main_proto_rawDescData = protoimpl.X.CompressGZIP(file_main_proto_rawDescData)
	})
	return file_main_proto_rawDescData
}

var file_main_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_main_proto_goTypes = []interface{}{
	(*SpinResponse)(nil), // 0: slot.SpinResponse
	(*Response)(nil),     // 1: slot.Response
	(*BaseResult)(nil),   // 2: slot.BaseResult
	(*FoodieBonus)(nil),  // 3: slot.FoodieBonus
	(*DragonBonus)(nil),  // 4: slot.DragonBonus
	(*Request)(nil),      // 5: slot.Request
}
var file_main_proto_depIdxs = []int32{
	2, // 0: slot.SpinResponse.res:type_name -> slot.BaseResult
	3, // 1: slot.SpinResponse.foodie:type_name -> slot.FoodieBonus
	4, // 2: slot.SpinResponse.dragon:type_name -> slot.DragonBonus
	0, // 3: slot.Response.spinResponse:type_name -> slot.SpinResponse
	5, // 4: slot.Slot.Spin:input_type -> slot.Request
	1, // 5: slot.Slot.Spin:output_type -> slot.Response
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_main_proto_init() }
func file_main_proto_init() {
	if File_main_proto != nil {
		return
	}
	file_base_request_proto_init()
	file_base_result_proto_init()
	file_foodie_proto_init()
	file_dragon_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_main_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_main_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*SpinResponse_Foodie)(nil),
		(*SpinResponse_Dragon)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_main_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_main_proto_goTypes,
		DependencyIndexes: file_main_proto_depIdxs,
		MessageInfos:      file_main_proto_msgTypes,
	}.Build()
	File_main_proto = out.File
	file_main_proto_rawDesc = nil
	file_main_proto_goTypes = nil
	file_main_proto_depIdxs = nil
}
