// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: base/request.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotId    uint32  `protobuf:"varint,1,opt,name=SlotId,proto3" json:"SlotId,omitempty"`
	BetCash   float32 `protobuf:"fixed32,2,opt,name=BetCash,proto3" json:"BetCash,omitempty"`
	BetLine   uint32  `protobuf:"varint,3,opt,name=BetLine,proto3" json:"BetLine,omitempty"`
	PrevState string  `protobuf:"bytes,4,opt,name=PrevState,proto3" json:"PrevState,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_base_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_base_request_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *Request) GetBetCash() float32 {
	if x != nil {
		return x.BetCash
	}
	return 0
}

func (x *Request) GetBetLine() uint32 {
	if x != nil {
		return x.BetLine
	}
	return 0
}

func (x *Request) GetPrevState() string {
	if x != nil {
		return x.PrevState
	}
	return ""
}

var File_base_request_proto protoreflect.FileDescriptor

var file_base_request_proto_rawDesc = []byte{
	0x0a, 0x12, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x22, 0x73, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x53, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x42, 0x65, 0x74, 0x43, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07,
	0x42, 0x65, 0x74, 0x43, 0x61, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x65, 0x74, 0x4c, 0x69,
	0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x42, 0x65, 0x74, 0x4c, 0x69, 0x6e,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x72, 0x65, 0x76, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x72, 0x65, 0x76, 0x53, 0x74, 0x61, 0x74, 0x65, 0x42,
	0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_base_request_proto_rawDescOnce sync.Once
	file_base_request_proto_rawDescData = file_base_request_proto_rawDesc
)

func file_base_request_proto_rawDescGZIP() []byte {
	file_base_request_proto_rawDescOnce.Do(func() {
		file_base_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_base_request_proto_rawDescData)
	})
	return file_base_request_proto_rawDescData
}

var file_base_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_base_request_proto_goTypes = []interface{}{
	(*Request)(nil), // 0: slot.Request
}
var file_base_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_base_request_proto_init() }
func file_base_request_proto_init() {
	if File_base_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_base_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_base_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_base_request_proto_goTypes,
		DependencyIndexes: file_base_request_proto_depIdxs,
		MessageInfos:      file_base_request_proto_msgTypes,
	}.Build()
	File_base_request_proto = out.File
	file_base_request_proto_rawDesc = nil
	file_base_request_proto_goTypes = nil
	file_base_request_proto_depIdxs = nil
}
